// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
	PORT: string;
	CLOUDFLARE_R2_ACCESS_KEY_ID: string;
	CLOUDFLARE_R2_SECRET_ACCESS_KEY: string;
	CLOUDFLARE_R2_BUCKET_NAME: string;
	CLOUDFLARE_R2_REGION: string;
	CLOUDFLARE_R2_ENDPOINT: string;
}
